name: Build and push devcontainer image
on:
  workflow_call:
    inputs:
      image-name:
        type: string
        description: Image name to push, including registry
        default: ghcr.io/${{ github.repository }}/devcontainer
      directory:
        type: string
        description: Directory contains `.devcontainer` directory
        default: .
      push:
        type: string
        description: Whether to push image to repository or not. Accepts `never` or `always`.
        default: always

jobs:
  update-devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: actual build
        # use devcontainer up instead of devcontainer build. See https://github.com/devcontainers/cli/issues/190
        run: |
          set -e

          npm install -g @devcontainers/cli
          devcontainer up --workspace-folder . --prebuild --build-no-cache

      - name: upload image
        uses: devcontainers/ci@c3e31cc561800ac318ed000e22ffc6713c93d009
        with:
          imageName: ${{ inputs.image-name }}
          subFolder: ${{ inputs.directory }}
          push: ${{ inputs.push }}
          noCache: true
